"""The guide, and the half of it that is generated.

Reference is the half of documentation that goes wrong quietly: nobody notices a
stale endpoint list until they have spent twenty minutes calling something that was
renamed. So the reference pages are read out of the code, and this is what fails when
the committed files stop matching it.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
GUIDE = ROOT / "docs" / "guide"

SECTIONS = {"Start here", "How to", "Reference", "Why it works this way"}


def pages():
    return sorted(GUIDE.glob("*.md"))


def front_matter(path: Path) -> dict:
    raw = path.read_text()
    assert raw.startswith("---"), f"{path.name} has no front matter"
    end = raw.index("\n---", 3)
    meta = {}
    for line in raw[4:end].split("\n"):
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    return meta


def test_the_guide_exists():
    assert len(pages()) >= 10, "the guide is thinner than it should be"


@pytest.mark.parametrize("path", pages(), ids=lambda p: p.name)
def test_every_page_is_navigable(path):
    meta = front_matter(path)
    # Without these a page cannot appear in the sidebar, and a page nobody can find
    # is a page that does not exist.
    assert meta.get("title"), f"{path.name} has no title"
    assert meta.get("section") in SECTIONS, f"{path.name}: bad section {meta.get('section')!r}"
    assert meta.get("summary"), f"{path.name} has no summary"
    assert meta.get("order", "").isdigit(), f"{path.name} has no order"


@pytest.mark.parametrize("path", pages(), ids=lambda p: p.name)
def test_every_page_has_one_title(path):
    body = path.read_text().split("\n---", 1)[1]
    h1s = [line for line in body.splitlines() if line.startswith("# ")]
    assert len(h1s) == 1, f"{path.name} has {len(h1s)} top-level headings"


def test_the_guide_covers_all_four_kinds_of_page():
    """Something to follow, something to do, something to look up, something to
    understand. A guide missing one of those has a hole its readers fall into."""
    found = {front_matter(p)["section"] for p in pages()}
    assert found == SECTIONS, f"missing: {SECTIONS - found}"


def test_internal_links_point_at_pages_that_exist():
    slugs = {p.stem for p in pages()}
    broken = []
    for path in pages():
        for line in path.read_text().splitlines():
            for chunk in line.split("](/docs/")[1:]:
                target = chunk.split(")")[0].split("#")[0]
                if target and target not in slugs:
                    broken.append(f"{path.name} → /docs/{target}")
    assert not broken, "links to pages that do not exist: " + ", ".join(broken)


def test_the_generated_reference_matches_the_code():
    """The check that makes generated documentation worth having.

    If this fails, the code changed and the committed reference did not. Run
    `make docs`; do not edit the generated files, because the next run overwrites
    them.
    """
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "gen_docs.py"), "--check"],
        capture_output=True, text=True, cwd=ROOT,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def _generated_names() -> list[str]:
    """The pages the generator actually writes, asked of the generator.

    This used to be every file named `reference-*`, which is a proxy that holds only
    while every reference page happens to be code-derived. `reference-versions.md`
    is not: it is a measured compatibility matrix, produced by installing each Lance
    and reading a real table, and there is nothing in the code for a generator to
    read it out of. Keying on the generator's own list keeps the guarantee where it
    belongs — a page gen_docs.py writes must say so — without deciding that a
    hand-written reference page is a mistake.
    """
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_docs

    return sorted(gen_docs.PAGES)


@pytest.mark.parametrize("name", _generated_names())
def test_generated_pages_say_they_are_generated(name):
    text = (ROOT / "docs" / "guide" / name).read_text()
    assert "generated: true" in text
    assert "GENERATED by scripts/gen_docs.py" in text


@pytest.mark.parametrize("path", [p for p in pages() if p.name not in _generated_names()],
                         ids=lambda p: p.name)
def test_hand_written_pages_do_not_claim_to_be_generated(path):
    """The other half of the same guarantee.

    A page carrying `generated: true` gets a badge in the interface saying editing it
    would be undone. On a page nothing regenerates, that badge is a lie that sends a
    contributor looking for the code behind it.
    """
    assert "generated: true" not in path.read_text()
