"""Generate the reference documentation from the code it describes.

    uv run python scripts/gen_docs.py        # write
    uv run python scripts/gen_docs.py --check # fail if stale

Reference is the half of documentation that goes wrong quietly. Nobody notices a
stale endpoint list until they have spent twenty minutes calling something that was
renamed, and prose written by hand about a table of constants will drift from the
constants within a month.

So the reference pages are not written. They are read out of the running code — the
FastAPI route table, the findings rules and their docstrings, the model registry, the
MCP tool descriptions — and `make test` fails if the committed files no longer match
what the code would produce. Editing the generated file is the wrong move by
construction; the code is the source, and this is a rendering of it.

Everything else in `docs/guide/` is written by a person, because tutorials and
explanations are judgement and cannot be derived from a source tree.
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "ingest"))

GUIDE = ROOT / "docs" / "guide"

BANNER = """<!-- GENERATED by scripts/gen_docs.py — do not edit.
     The code is the source; this is a rendering of it. Change the code and run
     `make docs`, or `make test` will tell you the two have drifted. -->
"""


def _first_paragraph(text: str | None) -> str:
    """The opening paragraph of a docstring, unwrapped into one line."""
    if not text:
        return ""
    para = text.strip().split("\n\n")[0]
    return " ".join(line.strip() for line in para.splitlines() if line.strip())


def _home_relative(path) -> str:
    """A default path as a reader should see it.

    The generator would otherwise write the home directory of whichever machine ran
    it into the documentation — wrong for every other reader, and different on every
    machine, so the drift check fails on CI over a difference that means nothing.
    Derived from the code either way; only the rendering is normalised.
    """
    text = str(path)
    home = str(Path.home())
    return text.replace(home, "~") if text.startswith(home) else text


def _summary(text: str | None) -> str:
    """The first sentence, for a table cell."""
    para = _first_paragraph(text)
    if not para:
        return ""
    for end in (". ", "? ", "! "):
        if end in para:
            return para.split(end)[0] + end.strip()
    return para


# --------------------------------------------------------------------- http api

def http_api() -> str:
    from fastapi import FastAPI
    from fastapi.routing import APIRoute

    from server.main import mount_routers

    # A full app, built here rather than imported from `server.main`, because the
    # module-level one mounts whatever the ambient environment asks for and a
    # reference page must describe the software rather than one deployment.
    # Generating this with `LANCESCOPE_KIOSK` set would otherwise silently delete
    # two sections and `--check` would fail on the next machine.
    app = FastAPI()
    mount_routers(app, kiosk_mode=False)

    def walk(routes):
        """Every APIRoute, including those inside an included router.

        This FastAPI keeps `include_router` results nested in an `_IncludedRouter`
        rather than flattening them into the app, so a naive pass over `app.routes`
        finds nothing at all — which is exactly the kind of quiet wrongness a
        hand-written endpoint list would also have, and would not have announced.
        """
        for route in routes:
            if isinstance(route, APIRoute):
                yield route
            elif (original := getattr(route, "original_router", None)) is not None:
                yield from walk(original.routes)

    groups: dict[str, list] = {"catalog": [], "intelligence": [], "settings": [],
                               "ingest": [], "demo": []}
    for route in walk(app.routes):
        path = route.path
        if path.startswith("/catalog"):
            key = "catalog"
        elif path.startswith("/intel"):
            key = "intelligence"
        elif path.startswith("/settings"):
            key = "settings"
        elif path.startswith("/ingest"):
            key = "ingest"
        else:
            key = "demo"
        groups[key].append(route)

    titles = {
        "catalog": ("The console", "Read-only. Nothing here writes to a dataset, and "
                    "nothing materialises a blob column."),
        "intelligence": ("The language layer", "Optional. Every route answers with "
                         "nothing configured, and says what is missing."),
        "settings": ("Configuration", "The only routes that write anything, and what "
                     "they write is the settings file."),
        "ingest": ("Creating a database", "The only routes permitted to write a "
                   "dataset, and the only ones that may create a table. They may "
                   "never modify one that already exists."),
        "demo": ("Ctrl-F for Video", "The demo's own routes. They return 503 when the "
                 "corpus is absent."),
    }

    out = [BANNER, "# HTTP API", "",
           "Every route the server serves, read from its own route table.", ""]

    for key, (title, note) in titles.items():
        routes = sorted(groups[key], key=lambda r: (r.path, sorted(r.methods)[0]))
        if not routes:
            continue
        out += [f"## {title}", "", note, "",
                "| method | path | what it does |", "| --- | --- | --- |"]
        for r in routes:
            method = "/".join(sorted(m for m in r.methods if m != "HEAD"))
            summary = _summary(inspect.getdoc(r.endpoint)) or "—"
            out.append(f"| `{method}` | `{r.path}` | {summary} |")
        out.append("")

    return "\n".join(out)


# --------------------------------------------------------------------- findings

def findings_reference() -> str:
    from server.intel import findings as f

    out = [BANNER, "# Findings", "",
           "What the console works out for itself. No model is involved in any of "
           "these: each is a rule over metadata Lance already reports, and each "
           "carries the numbers it was computed from.", "",
           "A rule that raises is reported rather than swallowed — the response "
           "carries `partial_analysis` and the rule that failed, because a broken "
           "check must not look like a clean table.", ""]

    for rule in f.RULES:
        name = rule.__name__.lstrip("_").replace("_", " ")
        doc = inspect.getdoc(rule) or ""
        out += [f"## {name}", "", _first_paragraph(doc) or "—", ""]
        rest = (doc.split("\n\n", 1)[1].strip() if "\n\n" in doc else "")
        if rest:
            out += [rest, ""]

    out += ["## Severities", "",
            "| severity | meaning |", "| --- | --- |",
            "| `warn` | worth acting on |",
            "| `note` | worth knowing, and often worth *not* acting on |", "",
            "## Where they appear", "",
            "Each finding names the panel holding the evidence it was derived from, "
            "so it renders beside those numbers as well as in Insights: "
            + ", ".join(f"`{p}`" for p in f.PANELS) + ".", "",
            "## Who is asking", "",
            "A panel says where a finding's evidence lives. A *facet* says whose "
            "question it answers, which is a different axis: an unindexed vector "
            "column is evidence on the Indices panel and a per-query cost to anyone "
            "running a retrieval eval. `GET "
            "/catalog/tables/{name}/findings?facet=training` narrows the response to "
            "one reader's question, and the MCP `table_findings` tool takes the same "
            "argument. Every rule still runs either way — a facet filters the "
            "findings, not the sweep, so a rule that fails is still reported to "
            "whoever asked.", "",
            "| facet | what it collects |", "| --- | --- |",
            "| `training` | what a training run pays for: a split too coarse to feed "
            "a loader's workers, a straggler fragment that decides the epoch, "
            "tombstones read on every pass, an unindexed vector column costing a "
            "scan per eval query, and what re-embedding would rewrite |", "",
            "It reports the layout and nothing about the data. Whether the labels "
            "are right, whether a split leaks, whether the corpus is any good — "
            "none of that is visible from a manifest, and the panel says so rather "
            "than implying a clean bill of health it cannot give.", ""]
    return "\n".join(out)


# -------------------------------------------------------------------- datascan

def datascan_reference() -> str:
    from server.intel import datascan as d

    out = [BANNER, "# Data checks", "",
           "What the console can work out by **reading the data**, as opposed to "
           "[Findings](/docs/reference-findings), which never opens a data file. "
           "These cost real bytes, so none of them runs unless somebody asks — and "
           "every one is priced before it does.", "",
           "Three properties, and they are the whole design.", "",
           "**Quoted first.** `POST /scan/tables/{name}/plan` weighs each check from "
           "the data-file footers, without opening a page. On a media table the "
           "quote carries the more interesting half: reading every video's "
           "descriptor costs kilobytes, and the gigabytes those descriptors point at "
           "are not read.", "",
           "**Stoppable, and it means it.** Cancelling a scan stops the work between "
           "batches and reports the bytes it had spent. This is the one place in the "
           "product where cancel means cancel — a Lance query cannot be interrupted, "
           "and the query panel says so rather than pretending otherwise.", "",
           "**Measured afterwards.** Every result carries what it actually read, "
           "drained from the same handle every other panel drains, so the quote can "
           "be checked against the outcome rather than believed.", ""]

    for check in d.CHECKS:
        doc = inspect.getdoc(check.run) or ""
        out += [f"## {check.id}", "", f"*{check.title}.*", "",
                _first_paragraph(doc) or "—", ""]
        rest = (doc.split("\n\n", 1)[1].strip() if "\n\n" in doc else "")
        if rest:
            out += [rest, ""]

    out += ["## When a check will not run", "",
            "A check reports the same three states a connection does — `available`, "
            "`unsupported`, `unverified` — with the reason attached. Two of them "
            "matter often:", "",
            "- **No default column.** Which column holds a label, and which holds a "
            "split, are not visible in a schema. Guessing produces a real-looking "
            "answer to a question nobody asked, so these checks ask instead.",
            "- **No vector index.** `near-duplicates` refuses rather than falling "
            "back to a brute scan, because the fallback is one full pass over every "
            "vector *per row sampled* — a bill nobody agreed to by pressing a button "
            "labelled check.", "",
            "## What none of these can tell you", "",
            "Said here because a panel of green ticks implies otherwise. They cannot "
            "tell you whether a label is **right**; they cannot find a duplicate the "
            "embedding does not encode; they cannot attribute drift to a cause; and "
            "near-duplicate results are approximate by construction, because the "
            "index they ask is.", ""]
    return "\n".join(out)


# ----------------------------------------------------------------------- models

def models_reference() -> str:
    from server.intel import registry

    out = [BANNER, "# Models and providers", "",
           "The registry is data, not logic. Prices are cached and carry the date "
           f"they were read — **{registry.PRICED_ON}**. A model that is not listed "
           "is still usable; it reports its cost as unknown rather than as a "
           "plausible guess.", "",
           "## Known models", "",
           "| model | provider | input $/MTok | output $/MTok | context | tools |",
           "| --- | --- | --- | --- | --- | --- |"]

    for m in registry.MODELS.values():
        ctx = f"{m.context:,}" if m.context else "—"
        out.append(
            f"| `{m.id}` | {m.provider} | ${m.input_usd_per_mtok:g} | "
            f"${m.output_usd_per_mtok:g} | {ctx} | {'yes' if m.tools else 'no'} |")

    out += ["", f"The default when a key is present is `{registry.ANTHROPIC_DEFAULT}`. "
            "Choosing a cheaper one is the operator's call, made in settings — not "
            "something this tool does quietly to save money.", "",
            "## Local models", "",
            "Anything `ollama list` shows can be used, and costs nothing. These two "
            "were measured against this repository's own natural-language-to-filter "
            "cases and got every one right:", ""]
    for name in registry.LOCAL_KNOWN_GOOD:
        out.append(f"- `{name}`")
    out += ["", "A local model not in that list is assumed to handle structured "
            "output and *not* to handle multi-turn tool use — the cautious "
            "assumption rather than the convenient one.", ""]
    return "\n".join(out)


# -------------------------------------------------------------------- mcp tools

def mcp_reference() -> str:
    import asyncio

    from server import mcp_server

    tools = asyncio.run(mcp_server.server.list_tools())

    out = [BANNER, "# Agent tools (MCP)", "",
           "The console's read surface, as tools an agent can call. Every one is the "
           "HTTP route called in process rather than a reimplementation of it, so "
           "the two surfaces cannot drift — and no tool here can materialise a blob "
           "column, because the route underneath it cannot.", "",
           "| tool | read-only | what it does |", "| --- | --- | --- |"]

    for t in sorted(tools, key=lambda t: t.name):
        ro = "yes" if (t.annotations and t.annotations.read_only_hint) else "no"
        out.append(f"| `{t.name}` | {ro} | {t.description or '—'} |")

    out += ["", "## What the server tells a caller", "",
            "```", mcp_server.INSTRUCTIONS, "```", ""]
    return "\n".join(out)


# ------------------------------------------------------------------ query modes

def query_reference() -> str:
    from server import query

    out = [BANNER, "# Query modes", "",
           "What a table can be asked, and what each mode costs to ask. A mode a "
           "table cannot answer is reported with a reason rather than returning "
           "nothing — a search that silently finds nothing looks exactly like a "
           "search that found nothing.", "",
           "| mode | needs | notes |", "| --- | --- | --- |",
           "| `scan` | nothing | a filter and a page of rows |",
           "| `fts` | an inverted index on a string column | uses the index; "
           "returns `_score` |",
           "| `vector` | a vector column | uses an ANN index if one exists and the "
           "metric matches; otherwise scans every row. Returns `_distance` |",
           "| `hybrid` | both of the above | two searches fused by rank, each leg "
           "costed separately |", "",
           "## Access paths", "",
           "Lance's plan says which path a query took, before it runs. These are the "
           "ones the console names:", "",
           "| operator | called | meaning |", "| --- | --- | --- |"]

    for token, name, meaning in query.PATHS:
        out.append(f"| `{token}` | {name} | {meaning} |")

    out += ["", "## Limits", "",
            f"- a page returns at most **{query.MAX_LIMIT}** rows",
            f"- a search returns at most **k = {query.MAX_K}**",
            f"- a request waits **{query.DEFAULT_TIMEOUT_S:g}s** by default, then "
            "stops waiting — Lance offers no way to interrupt a running scan, so "
            "the scan continues until it finishes",
            "", "## Heavy columns", "",
            "Vectors, binary columns and Blob V2 columns are never read into a "
            "result. They are described from the schema, and no parameter of any "
            "query route can expand one.", ""]
    return "\n".join(out)


# --------------------------------------------------------------- configuration

# What each exported credential is for. Keyed by the names in
# `server/credentials.py::EXPORTED`, so adding one there and not here shows up as an
# empty cell rather than as a silently undocumented variable.
_CREDENTIAL_PURPOSE = {
    "HF_TOKEN": "HuggingFace, for gated or private datasets and a higher rate limit",
    "HUGGING_FACE_HUB_TOKEN": "the same, under the name the Hub's own tools use",
    "AWS_ACCESS_KEY_ID": "S3, and any S3-compatible store",
    "AWS_SECRET_ACCESS_KEY": "S3, and any S3-compatible store",
    "AWS_SESSION_TOKEN": "S3 with temporary credentials",
    "AWS_REGION": "S3",
    "AWS_DEFAULT_REGION": "S3, if `AWS_REGION` is unset",
    "AWS_ENDPOINT": "an S3-compatible store — MinIO, R2, B2",
    "AWS_PROFILE": "a named profile from the shared AWS config",
    "AWS_ALLOW_HTTP": "an S3-compatible store reached over plain HTTP",
    "GOOGLE_APPLICATION_CREDENTIALS": "Google Cloud Storage, path to a key file",
    "GOOGLE_SERVICE_ACCOUNT": "Google Cloud Storage, path to a service account",
    "AZURE_STORAGE_ACCOUNT_NAME": "Azure — required for `az://`, which carries no "
                                  "account name of its own",
    "AZURE_STORAGE_ACCOUNT_KEY": "Azure",
    "AZURE_STORAGE_SAS_KEY": "Azure, with a shared access signature",
    "AZURE_STORAGE_TOKEN": "Azure, with a bearer token",
}


def _credential_purpose(name: str) -> str:
    return _CREDENTIAL_PURPOSE.get(name, "")


def configuration_reference() -> str:
    from server import credentials
    from server import settings as cfg
    from server.intel import cache
    from server.sources import lancedb_cloud, objectstore

    out = [BANNER, "# Configuration", "",
           "Two sources, one rule: **the environment wins.** A deployment that pins "
           "a root or exports a key should not be overridden by a file someone "
           "edited through a browser, and every surface that shows a resolved value "
           "also shows which of the two it came from.", "",
           "## Environment", "",
           "| variable | what it does |", "| --- | --- |",
           "| `LANCE_ROOT` | the database to read. Wins over any saved connection |",
           "| `LANCESCOPE_CONFIG` | where the settings file lives "
           f"(default `{_home_relative(cfg.settings_path())}`) |",
           "| `ANTHROPIC_API_KEY` | enables the Claude path; beats a stored key |",
           "| `LANCESCOPE_LLM_PROVIDER` | `"
           + "` · `".join(cfg.PROVIDERS) + "` (default: auto-detect) |",
           "| `OLLAMA_HOST` | as Ollama itself defines it "
           f"(default `{cfg.DEFAULT_OLLAMA_HOST}`) |",
           "| `LANCESCOPE_LLM_BASE_URL` | for an OpenAI-compatible endpoint |",
           "| `LANCESCOPE_LLM_API_KEY` | for an OpenAI-compatible endpoint |",
           "| `LANCESCOPE_CACHE` | cached answers "
           f"(default `{_home_relative(cache.cache_dir())}`) |",
           "| `LANCESCOPE_SPEND_CEILING` | dollars, per process. Refuses before "
           "spending past it |",
           "| `API_ORIGIN` | where the web app proxies `/api/*` |",
           "| `LANCESCOPE_NO_PLUGINS` | refuse to load third-party source adapters. "
           "Also implied by kiosk mode |", "",
           "## Storage credentials", "",
           "Read from the environment, or from a `.cred` file written as "
           "`KEY=value` lines. "
           "The environment wins, and every surface that resolves one reports which "
           "of the two it came from — never the value.", "",
           "Two places are searched, first that exists winning: `.cred` beside the "
           "project root, which is the one a checkout edits and `desktop/sign.sh` "
           "reads, and `.cred` beside `settings.json`. The second is there for the "
           "packaged app, which has no project root — so a token that only exists in "
           "a checkout cannot reach a build somebody installed. "
           f"`{credentials.CRED_FILE}` names a file outright and beats both.", "",
           "Give it mode 600. It holds the same class of secret as `settings.json`, "
           "which is written 0600, but this one is written by hand — so the server "
           "checks at startup and says so rather than assuming.", "",
           "These are exported into the process environment at startup rather than "
           "passed along, because the libraries that need them read the environment "
           "and nowhere else. That is also what makes them consistent: the same "
           "variable resolves the listing and the open, so a store that lists is a "
           "store that opens.", "",
           "| variable | for |", "| --- | --- |",
           *[f"| `{name}` | {_credential_purpose(name)} |"
             for name in credentials.EXPORTED],
           f"| `{lancedb_cloud.API_KEY}` | LanceDB Cloud and Enterprise |",
           f"| `{lancedb_cloud.REGION}` | LanceDB Cloud region "
           f"(default `{lancedb_cloud.DEFAULT_REGION}`) |",
           f"| `{lancedb_cloud.HOST_OVERRIDE}` | replaces the LanceDB endpoint "
           "entirely, for Enterprise |", "",
           "S3-compatible stores — MinIO, Cloudflare R2, Backblaze B2 — need no "
           "scheme of their own: point `AWS_ENDPOINT` at them and use `s3://`.", "",
           "## Source adapters", "",
           "Which schemes this build can list. A scheme with no adapter is saved and "
           "reported as unbrowsable rather than silently listing nothing; adding one "
           "is an installable package, documented in "
           "[Write a source adapter](/docs/howto-write-a-source).", "",
           "| scheme | listed through |", "| --- | --- |",
           "| *(none — a local path)* | a bounded directory walk |",
           "| `hf://` | the HuggingFace Hub API |",
           *[f"| `{scheme}://` | Lance's object store |"
             for scheme in objectstore.SCHEMES],
           "| `db://` | a Lance namespace, over REST |", "",
           "`GET /catalog/runtime` reports the same list at run time, including any "
           "adapter that failed to load and why.", "",
           "## The settings file", "",
           "Written at mode `0600`, because a stored API key would be in it. It is "
           "the only file this project writes, and it is never written inside a "
           "dataset directory.", "",
           "```json", """{
  "version": 1,
  "connections": [
    { "id": "…", "label": "…", "uri": "/path/to/tables", "added": "…" }
  ],
  "active_id": "…",
  "intelligence": {
    "enabled": true,
    "provider": "auto",
    "model": null,
    "model_fast": null,
    "spend_ceiling_usd": null
  }
}""", "```", "",
           "## Where the root comes from", "",
           "In order, first match wins:", "",
           "1. `LANCE_ROOT`\n2. the active saved connection\n"
           "3. the ingest output directory, **only if it holds tables**\n"
           "4. nothing — and the console says so rather than showing an empty "
           "database", ""]
    return "\n".join(out)


# Front matter lives here rather than in the generated files, because the files are
# rewritten wholesale and anything hand-added to them would be lost on the next run.
def cli_reference() -> str:
    """Every subcommand, read off the parser rather than described beside it.

    A hand-written CLI page drifts the first time a flag is added, and the drift is
    invisible: the page still reads correctly, it is just no longer true. This walks
    `build_parser()` so it cannot.
    """
    import argparse as ap

    from ingest.cli import build_parser

    parser = build_parser()
    subs = next(a for a in parser._actions if isinstance(a, ap._SubParsersAction))

    out = [BANNER, "# Command line", "",
           "`lancescope` is the same read and ingest surface the console uses, called "
           "in process. Two of these commands are meant for a script rather than a "
           "person: `findings --fail-on` is a build gate, and `run-config` writes an "
           "artifact to stdout with everything else on stderr.", "",
           "## Exit codes", "",
           "| code | meaning |", "| --- | --- |",
           "| 0 | it worked, or nothing was asked of it |",
           "| 1 | the gate fired — a finding at or above the requested severity |",
           "| 2 | a usage error: no such table, no such column, nothing configured |",
           "| 3 | a rule crashed, so the sweep was incomplete and proves nothing |",
           "| 130 | interrupted |", "",
           "A missing table is 2 rather than 1 on purpose. A job whose table was "
           "renamed and a job whose table has a warning on it need different people "
           "to look at them.", ""]

    for name, sub in subs.choices.items():
        out += [f"## `lancescope {name}`", ""]
        help_text = next((c.help for c in subs._choices_actions if c.dest == name), "")
        if help_text:
            out += [help_text[0].upper() + help_text[1:] + ".", ""]
        rows = []
        for action in sub._actions:
            if action.dest in ("help",):
                continue
            flags = ", ".join(f"`{o}`" for o in action.option_strings) or f"`{action.dest}`"
            # Every `--json` is declared without help text, deliberately and
            # consistently, because it means the same thing on every subcommand.
            # Saying so once here beats adding the same sentence six times.
            text = action.help or ("the same answer as an object, for a script"
                                   if action.dest == "json" else "")
            rows.append(f"| {flags} | {text} |")
        if rows:
            out += ["| flag | what it does |", "| --- | --- |", *rows, ""]
    return "\n".join(out)


PAGES = {
    "reference-configuration.md": (configuration_reference, dict(
        title="Configuration", order=1,
        summary="Every environment variable and settings field, and which one wins.")),
    "reference-query.md": (query_reference, dict(
        title="Query modes", order=2,
        summary="What a table can be asked, the access paths, and the limits.")),
    "reference-findings.md": (findings_reference, dict(
        title="Findings", order=3,
        summary="Every rule the console applies, and what each one checks.")),
    "reference-data-checks.md": (datascan_reference, dict(
        title="Data checks", order=3.5,
        summary="Checks that read the data, what each one costs, and what none of "
                "them can tell you.")),
    "reference-models.md": (models_reference, dict(
        title="Models and providers", order=4,
        summary="The registry: who serves what, what it costs, what it can do.")),
    "reference-mcp.md": (mcp_reference, dict(
        title="Agent tools", order=5,
        summary="The MCP tool set, and what the server tells a caller.")),
    "reference-http-api.md": (http_api, dict(
        title="HTTP API", order=6,
        summary="Every route, read from the server's own route table.")),
    "reference-cli.md": (cli_reference, dict(
        title="Command line", order=7,
        summary="Every subcommand and flag, read from the parser, and the exit codes.")),
}


def front_matter(meta: dict) -> str:
    return (f"---\ntitle: {meta['title']}\nsection: Reference\n"
            f"order: {meta['order']}\nsummary: {meta['summary']}\n"
            f"generated: true\n---\n\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed files are out of date")
    args = parser.parse_args()

    GUIDE.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, (build, meta) in PAGES.items():
        path = GUIDE / name
        fresh = front_matter(meta) + build().rstrip() + "\n"
        current = path.read_text() if path.exists() else ""
        if args.check:
            if current != fresh:
                stale.append(name)
        elif current != fresh:
            path.write_text(fresh)
            print(f"  wrote {path.relative_to(ROOT)}")

    if args.check and stale:
        print("These reference pages no longer match the code:")
        for name in stale:
            print(f"  {name}")
        print("\nRun `make docs`. Do not edit them by hand — the code is the source.")
        return 1
    if args.check:
        print(f"  {len(PAGES)} reference pages match the code")
    return 0


if __name__ == "__main__":
    sys.exit(main())
