"""Generate the reference documentation from the code it describes.

    uv run python scripts/gen_docs.py        # write
    uv run python scripts/gen_docs.py --check # fail if stale

Reference is the half of documentation that goes wrong quietly. Nobody notices a
stale endpoint list until they have spent twenty minutes calling something that was
renamed, and prose written by hand about a table of constants will drift from the
constants within a month.

So the reference pages are not written. They are read out of the running code — the
FastAPI route table, the findings rules and their docstrings, the model registry, the
MCP tool descriptions — and `make test` fails if the committed files no longer match
what the code would produce. Editing the generated file is the wrong move by
construction; the code is the source, and this is a rendering of it.

Everything else in `docs/guide/` is written by a person, because tutorials and
explanations are judgement and cannot be derived from a source tree.
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "ingest"))

GUIDE = ROOT / "docs" / "guide"

BANNER = """<!-- GENERATED by scripts/gen_docs.py — do not edit.
     The code is the source; this is a rendering of it. Change the code and run
     `make docs`, or `make test` will tell you the two have drifted. -->
"""


def _first_paragraph(text: str | None) -> str:
    """The opening paragraph of a docstring, unwrapped into one line."""
    if not text:
        return ""
    para = text.strip().split("\n\n")[0]
    return " ".join(line.strip() for line in para.splitlines() if line.strip())


def _home_relative(path) -> str:
    """A default path as a reader should see it.

    The generator would otherwise write the home directory of whichever machine ran
    it into the documentation — wrong for every other reader, and different on every
    machine, so the drift check fails on CI over a difference that means nothing.
    Derived from the code either way; only the rendering is normalised.
    """
    text = str(path)
    home = str(Path.home())
    return text.replace(home, "~") if text.startswith(home) else text


def _summary(text: str | None) -> str:
    """The first sentence, for a table cell."""
    para = _first_paragraph(text)
    if not para:
        return ""
    for end in (". ", "? ", "! "):
        if end in para:
            return para.split(end)[0] + end.strip()
    return para


# --------------------------------------------------------------------- http api

def http_api() -> str:
    from fastapi.routing import APIRoute

    from server.main import app

    def walk(routes):
        """Every APIRoute, including those inside an included router.

        This FastAPI keeps `include_router` results nested in an `_IncludedRouter`
        rather than flattening them into the app, so a naive pass over `app.routes`
        finds nothing at all — which is exactly the kind of quiet wrongness a
        hand-written endpoint list would also have, and would not have announced.
        """
        for route in routes:
            if isinstance(route, APIRoute):
                yield route
            elif (original := getattr(route, "original_router", None)) is not None:
                yield from walk(original.routes)

    groups: dict[str, list] = {"catalog": [], "intelligence": [], "settings": [],
                               "demo": []}
    for route in walk(app.routes):
        path = route.path
        if path.startswith("/catalog"):
            key = "catalog"
        elif path.startswith("/intel"):
            key = "intelligence"
        elif path.startswith("/settings"):
            key = "settings"
        else:
            key = "demo"
        groups[key].append(route)

    titles = {
        "catalog": ("The console", "Read-only. Nothing here writes to a dataset, and "
                    "nothing materialises a blob column."),
        "intelligence": ("The language layer", "Optional. Every route answers with "
                         "nothing configured, and says what is missing."),
        "settings": ("Configuration", "The only routes that write anything, and what "
                     "they write is the settings file."),
        "demo": ("Ctrl-F for Video", "The demo's own routes. They return 503 when the "
                 "corpus is absent."),
    }

    out = [BANNER, "# HTTP API", "",
           "Every route the server serves, read from its own route table.", ""]

    for key, (title, note) in titles.items():
        routes = sorted(groups[key], key=lambda r: (r.path, sorted(r.methods)[0]))
        if not routes:
            continue
        out += [f"## {title}", "", note, "",
                "| method | path | what it does |", "| --- | --- | --- |"]
        for r in routes:
            method = "/".join(sorted(m for m in r.methods if m != "HEAD"))
            summary = _summary(inspect.getdoc(r.endpoint)) or "—"
            out.append(f"| `{method}` | `{r.path}` | {summary} |")
        out.append("")

    return "\n".join(out)


# --------------------------------------------------------------------- findings

def findings_reference() -> str:
    from server.intel import findings as f

    out = [BANNER, "# Findings", "",
           "What the console works out for itself. No model is involved in any of "
           "these: each is a rule over metadata Lance already reports, and each "
           "carries the numbers it was computed from.", "",
           "A rule that raises is reported rather than swallowed — the response "
           "carries `partial_analysis` and the rule that failed, because a broken "
           "check must not look like a clean table.", ""]

    for rule in f.RULES:
        name = rule.__name__.lstrip("_").replace("_", " ")
        doc = inspect.getdoc(rule) or ""
        out += [f"## {name}", "", _first_paragraph(doc) or "—", ""]
        rest = (doc.split("\n\n", 1)[1].strip() if "\n\n" in doc else "")
        if rest:
            out += [rest, ""]

    out += ["## Severities", "",
            "| severity | meaning |", "| --- | --- |",
            "| `warn` | worth acting on |",
            "| `note` | worth knowing, and often worth *not* acting on |", "",
            "## Where they appear", "",
            "Each finding names the panel holding the evidence it was derived from, "
            "so it renders beside those numbers as well as in Insights: "
            + ", ".join(f"`{p}`" for p in f.PANELS) + ".", ""]
    return "\n".join(out)


# ----------------------------------------------------------------------- models

def models_reference() -> str:
    from server.intel import registry

    out = [BANNER, "# Models and providers", "",
           "The registry is data, not logic. Prices are cached and carry the date "
           f"they were read — **{registry.PRICED_ON}**. A model that is not listed "
           "is still usable; it reports its cost as unknown rather than as a "
           "plausible guess.", "",
           "## Known models", "",
           "| model | provider | input $/MTok | output $/MTok | context | tools |",
           "| --- | --- | --- | --- | --- | --- |"]

    for m in registry.MODELS.values():
        ctx = f"{m.context:,}" if m.context else "—"
        out.append(
            f"| `{m.id}` | {m.provider} | ${m.input_usd_per_mtok:g} | "
            f"${m.output_usd_per_mtok:g} | {ctx} | {'yes' if m.tools else 'no'} |")

    out += ["", f"The default when a key is present is `{registry.ANTHROPIC_DEFAULT}`. "
            "Choosing a cheaper one is the operator's call, made in settings — not "
            "something this tool does quietly to save money.", "",
            "## Local models", "",
            "Anything `ollama list` shows can be used, and costs nothing. These two "
            "were measured against this repository's own natural-language-to-filter "
            "cases and got every one right:", ""]
    for name in registry.LOCAL_KNOWN_GOOD:
        out.append(f"- `{name}`")
    out += ["", "A local model not in that list is assumed to handle structured "
            "output and *not* to handle multi-turn tool use — the cautious "
            "assumption rather than the convenient one.", ""]
    return "\n".join(out)


# -------------------------------------------------------------------- mcp tools

def mcp_reference() -> str:
    import asyncio

    from server import mcp_server

    tools = asyncio.run(mcp_server.server.list_tools())

    out = [BANNER, "# Agent tools (MCP)", "",
           "The console's read surface, as tools an agent can call. Every one is the "
           "HTTP route called in process rather than a reimplementation of it, so "
           "the two surfaces cannot drift — and no tool here can materialise a blob "
           "column, because the route underneath it cannot.", "",
           "| tool | read-only | what it does |", "| --- | --- | --- |"]

    for t in sorted(tools, key=lambda t: t.name):
        ro = "yes" if (t.annotations and t.annotations.read_only_hint) else "no"
        out.append(f"| `{t.name}` | {ro} | {t.description or '—'} |")

    out += ["", "## What the server tells a caller", "",
            "```", mcp_server.INSTRUCTIONS, "```", ""]
    return "\n".join(out)


# ------------------------------------------------------------------ query modes

def query_reference() -> str:
    from server import query

    out = [BANNER, "# Query modes", "",
           "What a table can be asked, and what each mode costs to ask. A mode a "
           "table cannot answer is reported with a reason rather than returning "
           "nothing — a search that silently finds nothing looks exactly like a "
           "search that found nothing.", "",
           "| mode | needs | notes |", "| --- | --- | --- |",
           "| `scan` | nothing | a filter and a page of rows |",
           "| `fts` | an inverted index on a string column | uses the index; "
           "returns `_score` |",
           "| `vector` | a vector column | uses an ANN index if one exists and the "
           "metric matches; otherwise scans every row. Returns `_distance` |",
           "| `hybrid` | both of the above | two searches fused by rank, each leg "
           "costed separately |", "",
           "## Access paths", "",
           "Lance's plan says which path a query took, before it runs. These are the "
           "ones the console names:", "",
           "| operator | called | meaning |", "| --- | --- | --- |"]

    for token, name, meaning in query.PATHS:
        out.append(f"| `{token}` | {name} | {meaning} |")

    out += ["", "## Limits", "",
            f"- a page returns at most **{query.MAX_LIMIT}** rows",
            f"- a search returns at most **k = {query.MAX_K}**",
            f"- a request waits **{query.DEFAULT_TIMEOUT_S:g}s** by default, then "
            "stops waiting — Lance offers no way to interrupt a running scan, so "
            "the scan continues until it finishes",
            "", "## Heavy columns", "",
            "Vectors, binary columns and Blob V2 columns are never read into a "
            "result. They are described from the schema, and no parameter of any "
            "query route can expand one.", ""]
    return "\n".join(out)


# --------------------------------------------------------------- configuration

def configuration_reference() -> str:
    from server import settings as cfg
    from server.intel import cache

    out = [BANNER, "# Configuration", "",
           "Two sources, one rule: **the environment wins.** A deployment that pins "
           "a root or exports a key should not be overridden by a file someone "
           "edited through a browser, and every surface that shows a resolved value "
           "also shows which of the two it came from.", "",
           "## Environment", "",
           "| variable | what it does |", "| --- | --- |",
           "| `LANCE_ROOT` | the database to read. Wins over any saved connection |",
           "| `LANCESCOPE_CONFIG` | where the settings file lives "
           f"(default `{_home_relative(cfg.settings_path())}`) |",
           "| `ANTHROPIC_API_KEY` | enables the Claude path; beats a stored key |",
           "| `LANCESCOPE_LLM_PROVIDER` | `"
           + "` · `".join(cfg.PROVIDERS) + "` (default: auto-detect) |",
           "| `OLLAMA_HOST` | as Ollama itself defines it "
           f"(default `{cfg.DEFAULT_OLLAMA_HOST}`) |",
           "| `LANCESCOPE_LLM_BASE_URL` | for an OpenAI-compatible endpoint |",
           "| `LANCESCOPE_LLM_API_KEY` | for an OpenAI-compatible endpoint |",
           "| `LANCESCOPE_CACHE` | cached answers "
           f"(default `{_home_relative(cache.cache_dir())}`) |",
           "| `LANCESCOPE_SPEND_CEILING` | dollars, per process. Refuses before "
           "spending past it |",
           "| `API_ORIGIN` | where the web app proxies `/api/*` |", "",
           "## The settings file", "",
           "Written at mode `0600`, because a stored API key would be in it. It is "
           "the only file this project writes, and it is never written inside a "
           "dataset directory.", "",
           "```json", """{
  "version": 1,
  "connections": [
    { "id": "…", "label": "…", "uri": "/path/to/tables", "added": "…" }
  ],
  "active_id": "…",
  "intelligence": {
    "enabled": true,
    "provider": "auto",
    "model": null,
    "model_fast": null,
    "spend_ceiling_usd": null
  }
}""", "```", "",
           "## Where the root comes from", "",
           "In order, first match wins:", "",
           "1. `LANCE_ROOT`\n2. the active saved connection\n"
           "3. the ingest output directory, **only if it holds tables**\n"
           "4. nothing — and the console says so rather than showing an empty "
           "database", ""]
    return "\n".join(out)


# Front matter lives here rather than in the generated files, because the files are
# rewritten wholesale and anything hand-added to them would be lost on the next run.
PAGES = {
    "reference-configuration.md": (configuration_reference, dict(
        title="Configuration", order=1,
        summary="Every environment variable and settings field, and which one wins.")),
    "reference-query.md": (query_reference, dict(
        title="Query modes", order=2,
        summary="What a table can be asked, the access paths, and the limits.")),
    "reference-findings.md": (findings_reference, dict(
        title="Findings", order=3,
        summary="Every rule the console applies, and what each one checks.")),
    "reference-models.md": (models_reference, dict(
        title="Models and providers", order=4,
        summary="The registry: who serves what, what it costs, what it can do.")),
    "reference-mcp.md": (mcp_reference, dict(
        title="Agent tools", order=5,
        summary="The MCP tool set, and what the server tells a caller.")),
    "reference-http-api.md": (http_api, dict(
        title="HTTP API", order=6,
        summary="Every route, read from the server's own route table.")),
}


def front_matter(meta: dict) -> str:
    return (f"---\ntitle: {meta['title']}\nsection: Reference\n"
            f"order: {meta['order']}\nsummary: {meta['summary']}\n"
            f"generated: true\n---\n\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed files are out of date")
    args = parser.parse_args()

    GUIDE.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, (build, meta) in PAGES.items():
        path = GUIDE / name
        fresh = front_matter(meta) + build().rstrip() + "\n"
        current = path.read_text() if path.exists() else ""
        if args.check:
            if current != fresh:
                stale.append(name)
        elif current != fresh:
            path.write_text(fresh)
            print(f"  wrote {path.relative_to(ROOT)}")

    if args.check and stale:
        print("These reference pages no longer match the code:")
        for name in stale:
            print(f"  {name}")
        print("\nRun `make docs`. Do not edit them by hand — the code is the source.")
        return 1
    if args.check:
        print(f"  {len(PAGES)} reference pages match the code")
    return 0


if __name__ == "__main__":
    sys.exit(main())
