"""Migration: four different operations that share a word and almost nothing else.

"Migrate this table" means at least four things, and collapsing them into one plan
would produce a document that is wrong about three of them:

- **format** — the table is on an older Lance storage version than this build writes
- **copy** — the same table somewhere else: a bucket, a cloud database, a laptop
- **schema** — a column added, retyped or dropped
- **embed** — the vectors regenerated by a different model

They differ in every field the plan contract has. A format migration rewrites
everything and changes no row; a copy changes nothing at the source and everything
about where the bytes live; a dropped column is a manifest edit that frees no space
until something compacts; and re-embedding produces a table that looks identical and
searches differently, which is the one failure on this list nobody notices from the
outside.

So: four functions, four kinds, and a refusal where this console genuinely cannot
answer.
"""

from __future__ import annotations

from server import estimate as est
from server.catalog import capabilities_for, disk_usage, is_blob_field
from server.ops import plan as P

# What `ingest/core/writer.py` pins for a table it creates. Kept as a string here
# rather than imported, because `server/` may not import `ingest` — and the failure
# direction is safe: a build that starts writing something newer makes this plan say
# a table is current when it is one version behind, which the storage version printed
# beside it contradicts on screen.
CURRENT_STORAGE_VERSION = "2.2"

# The table's own self-description, written into schema metadata at ingest under a
# public prefix. Read as data rather than imported as a constant: if the writer
# renames these, this reports "unknown", which is the right way for it to be wrong.
EMBEDDER_PREFIX = "lancescope.embedder."


def _metadata(ds) -> dict[str, str]:
    out = {}
    for k, v in (ds.schema.metadata or {}).items():
        key = k.decode() if isinstance(k, bytes) else str(k)
        val = v.decode() if isinstance(v, bytes) else str(v)
        out[key] = val
    return out


def _version_tuple(v: str) -> tuple[int, ...]:
    try:
        return tuple(int(p) for p in str(v).split("."))
    except ValueError:
        return (0,)


# --------------------------------------------------------------------------- format

def build_format(handle) -> P.OperationPlan:
    """A plan to bring the table onto the storage version this build writes."""
    ds = handle.ds
    handle.drain()
    uri, version = handle.uri, ds.version
    current = str(ds.data_storage_version)
    behind = _version_tuple(current) < _version_tuple(CURRENT_STORAGE_VERSION)

    costs = est.table_costs(handle)
    total = costs.file_bytes
    rows = ds.count_rows()
    d = handle.drain()

    return P.OperationPlan(
        kind=P.MIGRATE_FORMAT, table=handle.name, uri=uri, target_version=version,
        title=(f"Rewrite from storage format {current} to {CURRENT_STORAGE_VERSION}"
               if behind else f"Already on storage format {current}"),
        summary=(
            f"This table is on Lance storage format {current}; this build writes "
            f"{CURRENT_STORAGE_VERSION}. Moving it means rewriting every data file — "
            f"{total:,} bytes across {costs.files_total} file(s) — because a storage "
            f"version is a property of the files, not of the manifest."
            if behind else
            f"This table is already on {current}, which is what this build writes. "
            f"There is nothing to migrate."),
        preconditions=[
            P.Precondition(
                claim=f"the table is behind {CURRENT_STORAGE_VERSION}",
                holds=behind,
                detail=f"on {current}",
            ),
            P.Precondition(
                claim="there is room for a second copy while it is written",
                holds=True,
                detail=f"the rewrite is not in place; expect up to {total:,} extra "
                       f"bytes to exist at once",
            ),
        ],
        affected={"rows": rows, "files": costs.files_total, "bytes": total,
                  "from_format": current, "to_format": CURRENT_STORAGE_VERSION},
        estimate=P.Estimate(
            read_bytes=total, write_bytes=total, disk_delta_bytes=0,
            basis="file sizes from the manifest; a format migration reads and writes "
                  "every one of them"),
        reversible=False,
        rollback="None in place. The safe shape is to write a new table and swap the "
                 "connection once it verifies, keeping the original until it does — "
                 "which is why the script below writes to a new path rather than over "
                 "this one.",
        verification=(
            "Row count, schema and a sample query must match. The console's Compare "
            "tab works across versions of one table, not across two tables, so this "
            "one is checked by pointing a connection at the new path and reading the "
            "findings for both."),
        caveats=[
            "a storage-format migration is a full rewrite, not a manifest edit",
            "`migrate_manifest_paths_v2()` is a different and much cheaper thing — it "
            "changes how manifests are named, not how data is encoded",
        ],
        script=(
            "import lance\n\n"
            f"source = lance.dataset({uri!r})\n"
            f"assert source.version == {version}, \"table moved\"\n\n"
            "# Written to a new path on purpose: a format migration has no undo, and\n"
            "# a table you can still read is the only rollback there is.\n"
            "lance.write_dataset(\n"
            "    source.to_batches(),\n"
            f"    {uri + '.migrated'!r},\n"
            "    schema=source.schema,\n"
            f"    data_storage_version={CURRENT_STORAGE_VERSION!r},\n"
            "    mode='create',\n"
            ")\n"
        ) if behind else "",
        read_bytes=d.read_bytes, read_iops=d.read_iops,
    )


# ----------------------------------------------------------------------------- copy

def build_copy(handle, *, destination: str) -> P.OperationPlan:
    """A plan to put this table somewhere else."""
    ds = handle.ds
    handle.drain()
    uri, version = handle.uri, ds.version
    costs = est.table_costs(handle)
    rows = ds.count_rows()
    blob_columns = [f.name for f in ds.schema if is_blob_field(f)]

    # The manifest cannot see side files, so on a blob table `file_bytes` is the
    # small half of the answer and quoting it as the transfer size would understate
    # the move by orders of magnitude. `None` on a root that cannot be walked, which
    # is not the same claim as zero and is not reported as one.
    side = _side_bytes(handle) if blob_columns else 0
    total = costs.file_bytes + (side or 0)
    same_store = _store(uri) == _store(destination)
    d = handle.drain()

    return P.OperationPlan(
        kind=P.MIGRATE_COPY, table=handle.name, uri=uri, target_version=version,
        title=f"Copy {handle.name} to {_store(destination)}",
        summary=(
            f"{rows:,} rows, {total:,} bytes to move"
            + (f", of which {side:,} are Blob V2 side files the manifest does not "
               f"count" if side else "")
            + f". Source and destination are {'the same' if same_store else 'different'} "
              f"store{'s' if not same_store else ''}."),
        preconditions=[
            P.Precondition(
                claim="the destination is writable and empty",
                holds=False,
                detail="not checked — this console does not write, so it has not "
                       "probed the destination. Confirm it yourself before running.",
            ),
            P.Precondition(
                claim="credentials for the destination are configured",
                holds=False,
                detail="the same .cred file the console reads for connections; a "
                       "copy fails at the first object otherwise",
            ),
        ],
        affected={"rows": rows, "files": costs.files_total,
                  "bytes": total, "manifest_bytes": costs.file_bytes,
                  "blob_bytes": side, "blob_columns": blob_columns,
                  "destination": destination, "same_store": same_store},
        estimate=P.Estimate(
            read_bytes=total, write_bytes=total, disk_delta_bytes=total,
            basis=("manifest file sizes plus a filesystem walk of the blob side files"
                   if side else "file sizes from the manifest")),
        reversible=True,
        rollback="delete the destination. Nothing at the source is touched by a copy, "
                 "which is what makes this the safest operation in this module.",
        verification=(
            "Row counts and schema must match, and the findings for both should agree "
            "on everything except fragment layout — a copy re-fragments, and a "
            "different fragment count is expected rather than a fault."),
        caveats=(
            [f"{total:,} bytes over a network is the actual cost here; the console "
             f"measures bytes, not minutes, and cannot tell you how long that is"]
            + ([f"the {side:,} bytes in side files are the majority of this move and "
                f"are invisible to anything that reads only the manifest"]
               if side and side > costs.file_bytes else [])
            + (["a shallow clone would be near-instant, but only within one store — "
                "these are different stores, so the bytes have to move"]
               if not same_store else
               ["within one store, `shallow_clone` references the existing files "
                "instead of copying them; the script below copies, which is the "
                "portable answer"])),
        script=(
            "import lance\n\n"
            f"source = lance.dataset({uri!r})\n"
            f"assert source.version == {version}, \"table moved\"\n\n"
            "lance.write_dataset(\n"
            "    source.to_batches(),\n"
            f"    {destination!r},\n"
            "    schema=source.schema,\n"
            "    mode='create',\n"
            "    # storage_options={...} for credentials the environment does not carry\n"
            ")\n"
        ),
        read_bytes=d.read_bytes, read_iops=d.read_iops,
    )


def _side_bytes(handle) -> int | None:
    """Blob V2 side-file bytes for this table, or None where they cannot be walked.

    The same guard `server/estimate.py` uses: a remote root has no directory to walk,
    and reporting 0 there would say "this table has no side files" when the honest
    answer is "this console cannot see them".
    """
    if not capabilities_for(str(handle.uri)).disk_split.ok:
        return None
    try:
        return disk_usage(handle.uri, generation=handle.ds.version).blob_bytes or None
    except OSError:
        return None


def _store(uri: str) -> str:
    """The store a URI names — `s3://bucket`, `db://database`, or local disk."""
    if "://" not in uri:
        return "local disk"
    scheme, rest = uri.split("://", 1)
    return f"{scheme}://{rest.split('/', 1)[0]}"


# --------------------------------------------------------------------------- schema

def build_schema(handle, *, drop: list[str] | None = None,
                 alter: dict[str, str] | None = None) -> P.OperationPlan:
    """A plan to change this table's columns.

    Dropping and retyping are opposite in cost and it is not obvious which way round.
    A drop is a manifest edit: Lance stops reading the column and frees nothing until
    something rewrites the files. A retype rewrites the column everywhere it appears.
    A plan that reported both as "schema change" would be hiding the only number that
    matters.
    """
    ds = handle.ds
    handle.drain()
    uri, version = handle.uri, ds.version
    drop = list(drop or [])
    alter = dict(alter or {})
    known = {f.name for f in ds.schema}
    unknown = sorted((set(drop) | set(alter)) - known)

    if unknown:
        return P.unsupported(
            P.MIGRATE_SCHEMA, handle.name, uri, version,
            f"this table has no column(s) named {', '.join(repr(c) for c in unknown)}. "
            f"Its columns are: {', '.join(sorted(known))}")
    if not drop and not alter:
        return P.unsupported(
            P.MIGRATE_SCHEMA, handle.name, uri, version,
            "nothing to change — name the columns to drop or retype",
            state=P.UNVERIFIED)

    costs = est.table_costs(handle)
    dropped_bytes = sum(c.bytes for n, c in costs.columns.items() if n in drop)
    altered_bytes = sum(c.bytes for n, c in costs.columns.items() if n in alter)
    rows = ds.count_rows()
    d = handle.drain()

    lines = []
    for column in drop:
        lines.append(f"ds.drop_columns([{column!r}])")
    if alter:
        changes = ", ".join(
            f"{{'path': {c!r}, 'data_type': {t!r}}}" for c, t in alter.items())
        lines.append(f"ds.alter_columns({changes})")

    return P.OperationPlan(
        kind=P.MIGRATE_SCHEMA, table=handle.name, uri=uri, target_version=version,
        title=(f"Drop {len(drop)} column(s)" if drop and not alter else
               f"Retype {len(alter)} column(s)" if alter and not drop else
               f"Drop {len(drop)} and retype {len(alter)} column(s)"),
        summary=(
            (f"Dropping {', '.join(drop)} removes {dropped_bytes:,} bytes from every "
             f"read — but frees nothing on disk until the files are rewritten. " if drop else "")
            + (f"Retyping {', '.join(alter)} rewrites {altered_bytes:,} bytes."
               if alter else "")),
        preconditions=[
            P.Precondition(
                claim="nothing indexes the columns being changed",
                holds=not _indexed(ds, set(drop) | set(alter)),
                detail=(f"indexed: {', '.join(sorted(_indexed(ds, set(drop) | set(alter))))}"
                        if _indexed(ds, set(drop) | set(alter))
                        else "no index covers them"),
            ),
            P.Precondition(
                claim="no query or training run reads them",
                holds=False,
                detail="not something this console can know. A run-config generated "
                       "before this change will name a column that has gone.",
            ),
        ],
        affected={"rows": rows, "drop": drop, "alter": alter,
                  "dropped_bytes": dropped_bytes, "altered_bytes": altered_bytes,
                  "files": costs.files_total},
        estimate=P.Estimate(
            read_bytes=altered_bytes,
            write_bytes=altered_bytes,
            # The counter-intuitive one, stated as a number rather than a footnote.
            disk_delta_bytes=0 if drop and not alter else None,
            basis="column weights measured from the file footers. A drop is a "
                  "manifest edit and moves no bytes; a retype rewrites the column."),
        reversible=True,
        rollback=f"restore to version {version}. Both operations add a version and "
                 f"leave the old files in place until history is cleaned up.",
        verification=(
            f"Compare version {version} with the new one: the schema differs, the row "
            f"count must not. On a drop, the on-disk size will not fall — that is "
            f"correct, and compaction is what makes it fall."),
        caveats=(
            [f"dropping {', '.join(drop)} frees no disk space by itself. The bytes "
             f"stay in the data files until a compaction rewrites them."] if drop else []
        ) + (
            ["retyping casts every value. A cast that cannot represent a value fails "
             "the whole operation, which is better than a table half converted, but "
             "means it is worth validating the range first."] if alter else []),
        script=(
            "import lance\n\n"
            f"ds = lance.dataset({uri!r})\n"
            f"assert ds.version == {version}, f\"table moved to version {{ds.version}}\"\n\n"
            + "\n".join(lines) + "\n"
        ),
        read_bytes=d.read_bytes, read_iops=d.read_iops,
    )


def _indexed(ds, columns: set[str]) -> set[str]:
    out = set()
    for index in ds.list_indices():
        out |= columns & set(index.get("fields") or [])
    return out


# ---------------------------------------------------------------------------- embed

def build_embed(handle, *, column: str = "vector") -> P.OperationPlan:
    """Re-embedding, which this console can price and cannot verify.

    The cost is arithmetic and the risk is not. A re-embedded table looks identical:
    same rows, same schema, same fragment count, and a similarity search that returns
    plausible neighbours for the wrong reasons. The only thing that catches it is
    knowing which model produced the vectors that are there now — and the console can
    only know that if the table says so.
    """
    ds = handle.ds
    handle.drain()
    uri, version = handle.uri, ds.version
    meta = _metadata(ds)
    identity = {k[len(EMBEDDER_PREFIX):]: v for k, v in meta.items()
                if k.startswith(EMBEDDER_PREFIX)}
    field = next((f for f in ds.schema if f.name == column), None)

    if field is None:
        return P.unsupported(
            P.MIGRATE_EMBED, handle.name, uri, version,
            f"this table has no column named {column!r} to re-embed")

    if not identity:
        d = handle.drain()
        return P.unsupported(
            P.MIGRATE_EMBED, handle.name, uri, version,
            f"this table does not record which model produced {column!r}, so this "
            f"console cannot say what re-embedding would change. A vector column "
            f"replaced by a different model's output is the one migration that leaves "
            f"a table looking exactly as it did and searching differently — there is "
            f"nothing to compare against afterwards, so quoting a cost for it would "
            f"be pricing the easy half and staying quiet about the hard one.",
            state=P.UNVERIFIED,
            title=f"Re-embedding {column!r} cannot be planned from this table")

    rows = ds.count_rows()
    scan = est.scan_estimate(handle, [column])
    d = handle.drain()

    return P.OperationPlan(
        kind=P.MIGRATE_EMBED, table=handle.name, uri=uri, target_version=version,
        title=f"Re-embed {column!r} ({rows:,} rows)",
        summary=(
            f"The current vectors were produced by {identity.get('model', 'an unnamed model')}"
            + (f" ({identity.get('dim')} dimensions, {identity.get('metric', '?')} metric)"
               if identity.get("dim") else "")
            + f". Replacing them means running every row through a new model and "
              f"writing {scan.bytes:,} bytes of vectors back."),
        capability=P.Capability(P.AVAILABLE),
        preconditions=[
            P.Precondition(
                claim="the current model is recorded",
                holds=True,
                detail=", ".join(f"{k}={v}" for k, v in sorted(identity.items())),
            ),
            P.Precondition(
                claim="the new model's dimension is known and the index rebuilt for it",
                holds=False,
                detail="a vector index is built for one dimension and one metric. "
                       "Changing either without rebuilding leaves an index that "
                       "silently stops matching.",
            ),
        ],
        affected={"rows": rows, "column": column, "vector_bytes": scan.bytes,
                  "current_model": identity.get("model", ""),
                  "current_dim": identity.get("dim", ""),
                  "current_metric": identity.get("metric", "")},
        estimate=P.Estimate(
            read_bytes=None,
            write_bytes=scan.bytes,
            disk_delta_bytes=0,
            basis="the vector column's weight from the file footers. What the source "
                  "column costs to read and what inference costs are not modelled — "
                  "they depend on a model this console does not run."),
        reversible=True,
        rollback=f"restore to version {version}, while it is still there.",
        verification=(
            "Not a structural check. Row count and schema will match whatever "
            "happened, so hold out a set of known-good queries and compare their "
            "results before and after — this is the migration where the table looking "
            "right proves nothing."),
        caveats=[
            "re-embedding invalidates every vector index on the column; rebuild it",
            "record the new model in the table's metadata, or the next person is "
            "where this plan just was",
        ],
        script=(
            "# Re-embedding runs a model, which this console does not do.\n"
            "# The shape:\n"
            "#   1. read the source column the vectors were made from\n"
            "#   2. embed in batches with the new model\n"
            f"#   3. ds.merge(new_vectors, left_on=<key>)  # or write a new {column!r}\n"
            "#   4. rebuild the vector index for the new dimension and metric\n"
            "#   5. write the new model's identity into the schema metadata\n\n"
            "import lance\n\n"
            f"ds = lance.dataset({uri!r})\n"
            f"assert ds.version == {version}, \"table moved\"\n"
            f"# current: {', '.join(f'{k}={v}' for k, v in sorted(identity.items()))}\n"
        ),
        read_bytes=d.read_bytes, read_iops=d.read_iops,
    )
